_wandb:
    value:
        cli_version: 0.25.1
        e:
            grjpmvt1qd1n50ryzcff2t4nmundjaoa:
                apple: {}
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994610155520"
                        used: "215211761664"
                email: psuwimonopas@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
                git:
                    commit: 0c0385e3ed981cc2017ace8ca9502985d7314457
                    remote: https://github.com/BankDesu/Multi-Modal-Learning-of-Visual-Structural-and-Attention-Features-for-UX-Quality-Assessment.git
                host: Panachais-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-26.4.1-arm64-arm-64bit-Mach-O
                program: /Users/bankdesu/Works/KMUTT/Multi-Modal-Learning-of-Visual-Structural-and-Attention-Features-for-UX-Quality-Assessment/scripts/train.py
                python: CPython 3.13.12
                root: /Users/bankdesu/Works/KMUTT/Multi-Modal-Learning-of-Visual-Structural-and-Attention-Features-for-UX-Quality-Assessment
                startedAt: "2026-05-07T16:00:02.397512Z"
                writerId: grjpmvt1qd1n50ryzcff2t4nmundjaoa
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.13.12
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
batch_size:
    value: 4
detector_backend:
    value: yolo
epochs:
    value: 50
image_size:
    value: 224
lr:
    value: 0.0001
output_dim:
    value: 128
train_size:
    value: 800
val_size:
    value: 100
